export async function seed(knex) {
  await knex("tasks").del();

  await knex("tasks").insert([
    {
      id: 1,
      project_id: 1,
      assignee_id: 2,
      title: "Design CRM Database Schema",
      description: "Create database tables and relationships for CRM modules.",
      status: "done",
      priority: "high",
      due_date: "2026-06-15",
    },
    {
      id: 2,
      project_id: 1,
      assignee_id: 3,
      title: "Implement Customer Module",
      description: "Develop customer management functionality.",
      status: "in_progress",
      priority: "critical",
      due_date: "2026-07-15",
    },
    {
      id: 3,
      project_id: 1,
      assignee_id: 4,
      title: "Create Reporting Dashboard",
      description: "Build analytics dashboard for CRM insights.",
      status: "todo",
      priority: "medium",
      due_date: "2026-08-01",
    },
    {
      id: 4,
      project_id: 2,
      assignee_id: 2,
      title: "Upgrade Payment Gateway",
      description: "Integrate new payment gateway APIs.",
      status: "in_review",
      priority: "high",
      due_date: "2026-07-20",
    },
    {
      id: 5,
      project_id: 2,
      assignee_id: 3,
      title: "Optimize Product Search",
      description: "Improve search speed and relevance.",
      status: "cancelled",
      priority: "medium",
      due_date: "2026-07-10",
    },
    {
      id: 6,
      project_id: 3,
      assignee_id: 4,
      title: "Employee Profile Management",
      description: "Create employee profile and document storage module.",
      status: "done",
      priority: "high",
      due_date: "2026-03-15",
    },
    {
      id: 7,
      project_id: 4,
      assignee_id: 2,
      title: "User Authentication Module",
      description: "Implement JWT authentication and authorization.",
      status: "done",
      priority: "critical",
      due_date: "2026-07-01",
    },
    {
      id: 8,
      project_id: 4,
      assignee_id: 3,
      title: "Account Summary Screen",
      description: "Develop banking dashboard UI.",
      status: "in_progress",
      priority: "high",
      due_date: "2026-08-10",
    },
    {
      id: 9,
      project_id: 5,
      assignee_id: 4,
      title: "Stock Tracking Module",
      description: "Track inventory movement and stock levels.",
      status: "todo",
      priority: "medium",
      due_date: "2026-08-20",
    },
    {
      id: 10,
      project_id: 5,
      assignee_id: 3,
      title: "Inventory Reports",
      description: "Generate warehouse and stock reports.",
      status: "todo",
      priority: "low",
      due_date: "2026-09-01",
    },
  ]);
}
